# Generated by Django 3.0.4 on 2020-04-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('elevation_unit', models.CharField(max_length=15)),
                ('data_coverage', models.FloatField()),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
            ],
        ),
    ]
