# Generated by Django 3.0.4 on 2020-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHCND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('datatype', models.CharField(blank=True, choices=[('PRCP', 'Precipitation (mm)'), ('SNOW', 'Snowfall (mm)'), ('SNWD', 'Snow depth (mm)'), ('TMAX', 'Maximum temperature (C)'), ('TMIN', 'Minimum temperature (C)')], max_length=20, null=True)),
                ('attributes', models.CharField(max_length=15)),
                ('value', models.FloatField()),
            ],
        ),
    ]
